-- Internal concierge CRM (clients.kaykitay.ru). Consultant-only.
--
-- Tracks students who have ALREADY paid for full сопровождение — not leads.
-- Same Supabase project as StudyTrack; same is_consultant() gate the rest of
-- the admin surface uses. No student-facing access at any layer.
--
-- Additive-only: two new tables + one trigger function. Nothing existing is
-- touched. Safe to apply on the live DB and safe to re-run (guards throughout).

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table if not exists public.crm_clients (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  parent_name text,
  telegram_id text,

  anketa_done boolean not null default false,
  anketa_link text,
  podbor_link text,

  stage text not null default 'anketa',
  stage_deadline timestamptz,
  date_x date,

  program text not null default 'bachelor',

  -- Free-form content area (text / checklist / exam_table blocks). JSONB rather
  -- than a normalized block schema because shape and order vary freely per
  -- client and don't need relational querying at that granularity. The
  -- filterable fields (stage, dates, program) stay real typed columns above so
  -- they CAN be queried/filtered.
  blocks jsonb not null default '[]'::jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

create table if not exists public.crm_client_universities (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.crm_clients(id) on delete cascade,
  university_name text not null,
  program text,             -- free text: explorer program labels are browsing
                            -- categories, not the literal program name a uni uses
  university_source text,   -- 'explorer' | 'manual'
  added_at timestamptz not null default now()
);

create index if not exists crm_client_universities_client_id_idx
  on public.crm_client_universities (client_id);

-- ---------------------------------------------------------------------------
-- updated_at trigger
-- ---------------------------------------------------------------------------

create or replace function public.crm_set_updated_at()
returns trigger
language plpgsql
as $fn$
begin
  new.updated_at = now();
  return new;
end;
$fn$;

drop trigger if exists crm_clients_set_updated_at on public.crm_clients;
create trigger crm_clients_set_updated_at
  before update on public.crm_clients
  for each row execute function public.crm_set_updated_at();

-- ---------------------------------------------------------------------------
-- Row Level Security — consultant-only, everywhere
-- ---------------------------------------------------------------------------

alter table public.crm_clients enable row level security;
alter table public.crm_client_universities enable row level security;

drop policy if exists "Consultants manage clients" on public.crm_clients;
create policy "Consultants manage clients"
on public.crm_clients for all to authenticated
using (public.is_consultant()) with check (public.is_consultant());

drop policy if exists "Consultants manage client universities" on public.crm_client_universities;
create policy "Consultants manage client universities"
on public.crm_client_universities for all to authenticated
using (public.is_consultant()) with check (public.is_consultant());

-- Note: routes also go through the service-role client behind getConsultantUser(),
-- which bypasses RLS. These policies are the second layer — anon has no
-- applicable policy (fails closed) and a non-consultant authenticated user
-- matches none either.
