-- University Bank + per-student shortlists (admin-only tool).
--
-- A reusable bank of researched university+program rows, so a shortlist for a
-- new premium client is assembled from existing research instead of redoing it
-- every time. Shortlist items are SNAPSHOTS of the bank row at add-time, not
-- live links: editing a bank row later must not silently change a shortlist
-- that was already handed to a student.
--
-- Consultant-only at every layer. RLS is keyed on public.is_consultant()
-- (SECURITY DEFINER, see supabase-admin.sql) — the same gate the rest of the
-- admin surface uses. No student-facing access.
--
-- Additive-only: three new tables, nothing existing is touched. Safe to apply
-- on the live DB and safe to re-run (guards throughout).

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table if not exists public.university_bank (
  id bigint generated by default as identity primary key,
  university_name text not null,
  program text not null,
  city text,
  link text,
  arwu text,
  china_rank text,
  tuition text,
  exam_requirements text,
  deadline text,
  dorm_cost text,
  notes text,
  verified_at timestamptz,
  verified_by text,               -- 'Ашот' | 'Яна', free text is fine
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- One bank row per university+program combo. This uniqueness IS the point of
-- the whole system: it's what collapses "two students both had Sichuan
-- University — Software Engineering researched independently" into one row.
create unique index if not exists university_bank_uni_program_uniq
  on public.university_bank (lower(university_name), lower(program));

create table if not exists public.student_shortlists (
  id uuid primary key default gen_random_uuid(),
  student_name text not null,
  parent_name text,
  created_by text,                -- 'Ашот' | 'Яна'
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shortlist_items (
  id bigint generated by default as identity primary key,
  shortlist_id uuid not null references public.student_shortlists(id) on delete cascade,
  -- Kept for traceability ("where did this number come from"), allowed to go
  -- null if the bank row is ever deleted — the snapshot columns below are the
  -- real source of truth for this student's export.
  bank_id bigint references public.university_bank(id) on delete set null,
  university_name text not null,
  program text not null,
  city text,
  link text,
  arwu text,
  china_rank text,
  tuition text,
  exam_requirements text,
  deadline text,
  dorm_cost text,
  notes text,
  added_at timestamptz not null default now()
);

create index if not exists shortlist_items_shortlist_id_idx
  on public.shortlist_items (shortlist_id);

-- ---------------------------------------------------------------------------
-- Row Level Security — consultant-only, everywhere
-- ---------------------------------------------------------------------------

alter table public.university_bank enable row level security;
alter table public.student_shortlists enable row level security;
alter table public.shortlist_items enable row level security;

drop policy if exists "Consultants can read bank" on public.university_bank;
create policy "Consultants can read bank"
on public.university_bank for select to authenticated
using (public.is_consultant());

drop policy if exists "Consultants can insert bank" on public.university_bank;
create policy "Consultants can insert bank"
on public.university_bank for insert to authenticated
with check (public.is_consultant());

drop policy if exists "Consultants can update bank" on public.university_bank;
create policy "Consultants can update bank"
on public.university_bank for update to authenticated
using (public.is_consultant()) with check (public.is_consultant());

drop policy if exists "Consultants can delete bank" on public.university_bank;
create policy "Consultants can delete bank"
on public.university_bank for delete to authenticated
using (public.is_consultant());

drop policy if exists "Consultants can manage shortlists" on public.student_shortlists;
create policy "Consultants can manage shortlists"
on public.student_shortlists for all to authenticated
using (public.is_consultant()) with check (public.is_consultant());

drop policy if exists "Consultants can manage shortlist items" on public.shortlist_items;
create policy "Consultants can manage shortlist items"
on public.shortlist_items for all to authenticated
using (public.is_consultant()) with check (public.is_consultant());

-- Note: every route also goes through the service-role client behind
-- getConsultantUser(), which bypasses RLS. These policies are the second layer
-- — they make the tables safe even if reached directly through PostgREST with
-- an anon or authenticated key (anon has no applicable policy, so it fails
-- closed; a non-consultant authenticated user matches none either).
