create type public.student_role as enum ('student', 'parent', 'consultant');
create type public.application_status as enum ('applied', 'response', 'enrolled', 'rejected', 'planned');
create type public.document_status as enum ('not_started', 'in_progress', 'completed', 'uploaded');
create type public.stage_status as enum ('completed', 'current', 'pending');

create table public.students (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text not null,
  phone text,
  telegram_chat_id text,
  role public.student_role not null default 'student',
  -- Least privilege: a row created without these named must not come out paid.
  -- Both INSERT paths set them explicitly; these defaults are the backstop for
  -- any future one that forgets. Premium is always opt-in.
  service_type text default 'diy',
  subscription_status text default 'trial',
  pin_code text,
  -- Paid access is a one-time purchase covering a fixed window (see
  -- supabase-access-window.sql). NULL = never expires: staff, and anyone who
  -- bought before the window existed.
  access_expires_at timestamptz,
  -- Consent captured at registration. terms_accepted_at is mandatory (the API
  -- refuses registration without it); marketing_consent is opt-in and must be
  -- checked before any promotional send.
  terms_accepted_at timestamptz,
  marketing_consent boolean not null default false,
  marketing_consent_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.universities (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.students(id) on delete cascade,
  name text not null,
  status public.application_status not null default 'planned',
  deadline date,
  portal_url text,
  consultant_note text,
  order_index integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.university_history (
  id bigint generated by default as identity primary key,
  university_id bigint not null references public.universities(id) on delete cascade,
  event_date date,
  event text not null,
  order_index integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.documents (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.students(id) on delete cascade,
  name text not null,
  status public.document_status not null default 'not_started',
  deadline date,
  file_url text,
  uploaded_at timestamptz,
  order_index integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.deadlines (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.students(id) on delete cascade,
  title text not null,
  date date not null,
  university_name text not null,
  context text,
  is_urgent boolean not null default false,
  order_index integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.roadmap_stages (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.students(id) on delete cascade,
  stage_name text not null,
  status public.stage_status not null default 'pending',
  description text,
  order_index integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.next_actions (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.students(id) on delete cascade,
  title text not null,
  deadline date,
  action_button_text text not null default 'Открыть',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.students enable row level security;
alter table public.universities enable row level security;
alter table public.university_history enable row level security;
alter table public.documents enable row level security;
alter table public.deadlines enable row level security;
alter table public.roadmap_stages enable row level security;
alter table public.next_actions enable row level security;

create policy "Students can read own profile"
on public.students for select
to authenticated
using (id = auth.uid());

create policy "Students can read own universities"
on public.universities for select
to authenticated
using (student_id = auth.uid());

create policy "Students can update own universities"
on public.universities for update
to authenticated
using (student_id = auth.uid())
with check (student_id = auth.uid());

create policy "Students can read own university history"
on public.university_history for select
to authenticated
using (
  exists (
    select 1 from public.universities
    where universities.id = university_history.university_id
    and universities.student_id = auth.uid()
  )
);

create policy "Students can read own documents"
on public.documents for select
to authenticated
using (student_id = auth.uid());

create policy "Students can update own documents"
on public.documents for update
to authenticated
using (student_id = auth.uid())
with check (student_id = auth.uid());

create policy "Students can read own deadlines"
on public.deadlines for select
to authenticated
using (student_id = auth.uid());

create policy "Students can read own roadmap"
on public.roadmap_stages for select
to authenticated
using (student_id = auth.uid());

create policy "Students can read own next actions"
on public.next_actions for select
to authenticated
using (student_id = auth.uid());
