-- Migration: Add DIY/Premium segmentation and subscription tracking
-- Run this in your Supabase SQL Editor

-- Add service_type to students table
ALTER TABLE students
ADD COLUMN IF NOT EXISTS service_type TEXT NOT NULL DEFAULT 'premium'
CHECK (service_type IN ('diy', 'premium'));

-- Add subscription_status for DIY users
ALTER TABLE students
ADD COLUMN IF NOT EXISTS subscription_status TEXT NOT NULL DEFAULT 'active'
CHECK (subscription_status IN ('trial', 'active', 'inactive'));

-- Add pin_code for DIY subscription unlock
ALTER TABLE students
ADD COLUMN IF NOT EXISTS pin_code TEXT;

-- Add comment to explain the fields
COMMENT ON COLUMN students.service_type IS 'diy = self-service, premium = consultant-managed';
COMMENT ON COLUMN students.subscription_status IS 'trial = first 2 blocks free, active = paid via PIN, inactive = expired';
COMMENT ON COLUMN students.pin_code IS 'Unique PIN generated by admin for DIY users to unlock paid content';

-- Create index for faster filtering
CREATE INDEX IF NOT EXISTS idx_students_service_type ON students(service_type);
CREATE INDEX IF NOT EXISTS idx_students_subscription_status ON students(subscription_status);
